# spaceship
SPACESHIPS_SPEED = 4
SPACESHIPS_SIZE = (70, 70)
SPACESHIPS_HEALTH = 100

# EXPLOSIVE
# bullet
EXPLOSIVE_BULLET_SPEED = 12
EXPLOSIVE_BULLET_SIZE = (25, 25)
EXPLOSIVE_BULLET_IMAGE = './Textures/bullet.png'
# perk
EXPLOSIVE_PERK_COOLDOWN = 1000
EXPLOSIVE_PERK_COUNTDOWN = 5000
EXPLOSIVE_DAMAGE = 50
# perk animation
EXPLOSIVE_ANIMATION_IMAGE = './Textures/ExplosiveAnimation.png'
EXPLOSIVE_ANIMATION_COUNT_OF_FRAMES = 12
EXPLOSIVE_ANIMATION_TICKS_PER_FRAME = 10
